"""add squad names

Revision ID: 1b0d09ca81b1
Revises: 757be2ea2041
Create Date: 2023-12-24 00:18:22.544256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b0d09ca81b1'
down_revision = '757be2ea2041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squad', schema=None) as batch_op:
        batch_op.drop_index('ix_squad_name')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=64), nullable=False))
        batch_op.create_index('ix_squad_name', ['name'], unique=False)

    # ### end Alembic commands ###
