"""users table

Revision ID: 4993f6eda2d2
Revises: 
Create Date: 2023-12-23 14:57:28.905240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4993f6eda2d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('teamname', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_teamname'), ['teamname'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.drop_table('Squads')
    op.drop_table('Games')
    op.drop_table('Teams')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Teams',
    sa.Column('TEAMID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NAME', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ABBR', mysql.VARCHAR(length=5), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Games',
    sa.Column('GAMEID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('TEAMID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('RESULT', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('GAMEDATE', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('GAMEID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Squads',
    sa.Column('USERID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('TEAMID', mysql.INTEGER(), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_teamname'))

    op.drop_table('user')
    # ### end Alembic commands ###
