"""fix + remove squad from game

Revision ID: 4cae302106b2
Revises: 441ae8a1977d
Create Date: 2023-12-23 15:21:01.010455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4cae302106b2'
down_revision = '441ae8a1977d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_constraint('game_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('game_ibfk_4', type_='foreignkey')
        batch_op.drop_column('home_team_squad_id')
        batch_op.drop_column('away_team_squad_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('away_team_squad_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('home_team_squad_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('game_ibfk_4', 'squad', ['home_team_squad_id'], ['id'])
        batch_op.create_foreign_key('game_ibfk_2', 'squad', ['away_team_squad_id'], ['id'])

    # ### end Alembic commands ###
