"""allow null

Revision ID: 7315fd150d07
Revises: 5c8d2d40ee53
Create Date: 2023-12-23 18:05:13.257126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7315fd150d07'
down_revision = '5c8d2d40ee53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_picture',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
        batch_op.drop_index('ix_user_profile_picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_profile_picture', ['profile_picture'], unique=False)
        batch_op.alter_column('profile_picture',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###
