"""add squad names

Revision ID: 757be2ea2041
Revises: b1ae02834dd0
Create Date: 2023-12-24 00:16:52.475232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '757be2ea2041'
down_revision = 'b1ae02834dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('squad_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('squad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['squad_id'], ['squad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('squad_name', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_squad_name_name'), ['name'], unique=True)

    with op.batch_alter_table('squad', schema=None) as batch_op:
        batch_op.drop_index('ix_squad_name')
        batch_op.create_index(batch_op.f('ix_squad_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squad', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_squad_name'))
        batch_op.create_index('ix_squad_name', ['name'], unique=True)

    with op.batch_alter_table('squad_name', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_squad_name_name'))

    op.drop_table('squad_name')
    # ### end Alembic commands ###
